name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - New WHATWG DOM API
        - Performance improvement
        - Developer experience
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Why do you need this feature? What problem does it solve?
      placeholder: This would help with...
    validations:
      required: true

  - type: textarea
    id: spec-reference
    attributes:
      label: WHATWG Spec Reference
      description: If applicable, which part of the WHATWG DOM spec covers this?
      placeholder: "Section X.Y.Z of https://dom.spec.whatwg.org/"
    validations:
      required: false

  - type: textarea
    id: proposed-api
    attributes:
      label: Proposed API
      description: What would the API look like?
      render: zig
      placeholder: |
        // Example API usage
        const result = try element.newMethod();
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative approaches?
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have checked that this feature hasn't already been requested
          required: true
        - label: This feature aligns with the WHATWG DOM specification
          required: false
        - label: I am willing to help implement this feature
          required: false
